const booksData = [
  {
    id: 1,
    title: "Atomic Habits",
    author: "James Clear",
    year: 2018,
    cover: "https://covers.openlibrary.org/b/id/9251981-L.jpg",
    subject: "Self Improvement",
    description: "Buku ini adalah panduan untuk membentuk kebiasaan kecil yang menghasilkan perubahan besar dalam hidup.",
  },
  {
    id: 2,
    title: "Deep Work",
    author: "Cal Newport",
    year: 2016,
    cover: "https://covers.openlibrary.org/b/id/8379553-L.jpg",
    subject: "Productivity",
    description: "Tentang cara meningkatkan fokus dan performa dalam dunia yang penuh distraksi.",
  },
  {
    id: 3,
    title: "Clean Code",
    author: "Robert C. Martin",
    year: 2008,
    cover: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    subject: "Software Engineering",
    description: "Berisikan pedoman menulis kode yang bersih, mudah dibaca, dan mudah dipelihara.",
  },
  {
    id: 4,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    year: 2011,
    cover: "https://covers.openlibrary.org/b/id/8235110-L.jpg",
    subject: "Psychology",
    description: "Eksplorasi cara kerja dua sistem berpikir manusia: cepat intuitif dan lambat rasional.",
  },
  {
    id: 5,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    year: 1999,
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    subject: "Programming",
    description: "Buku klasik tentang filosofi dan praktik pengembangan perangkat lunak profesional, untuk mengetauhi cara menjadi software engineer yang lebih baik.",
  },
  {
    id: 6,
    title: "The Lean Startup",
    author: "Eric Ries",
    year: 2011,
    cover: "https://covers.openlibrary.org/b/id/8234621-L.jpg",
    subject: "Business",
    description: "Metodologi membangun startup yang efisien melalui eksperimen cepat dan pembelajaran berkelanjutan.",
  },
  {
    id: 7,
    title: "You Don’t Know JS",
    author: "Kyle Simpson",
    year: 2015,
    cover: "https://covers.openlibrary.org/b/id/8226199-L.jpg",
    subject: "Programming",
    description: "Seri buku mendalam tentang konsep JavaScript modern dan advanced.",
  },
  {
    id: 8,
    title: "The Design of Everyday Things",
    author: "Don Norman",
    year: 1988,
    cover: "https://covers.openlibrary.org/b/id/8225402-L.jpg",
    subject: "Design",
    description: "Penjelasan mendalam tentang desain produk yang mudah digunakan dan intuitif, serta prinsip-prinsip desain yang baik.",
  },
  {
    id: 9,
    title: "40 Resep Masakan Sehari-Hari : Praktis & Lezat",
    author: "Dewi Soesilo",
    year: 2016,
    cover: "https://static.mizanstore.com/d/img/book/cover/DE001357.jpg",
    subject: "Resep Makanan",
    description: "Segera ubah menu lauk kita dengan menjadikan buku ini sebagai panduan memasak. Selain berisikan lebih dari 40 resep lauk, sayur, dan sambal, buku ini juga disertai dengan tips memasak.",
  },
  {
    id: 10,
    title: "Educated",
    author: "Tara Westover",
    year: 2018,
    cover: "https://covers.openlibrary.org/b/id/9255301-L.jpg",
    subject: "Memoir",
    description: "Kisah nyata perjuangan seorang perempuan keluar dari keluarga ekstremis untuk menuntut ilmu.",
  },
  {
    id: 11,
    title: "Politik Identitas Kesaktian Dan Kekuasaan",
    author: "Otto Sukatno, CR",
    year: 2018,
    cover: "https://tirtabuanamedia.co.id/wp-content/uploads/2023/01/Politik-Identitas-Kesaktian-Dan-Kekuasaan.jpg",
    subject: "Politik",
    description: "Membahas tentang bagaimana identitas kesaktian (baik yang supranatural maupun simbolis) digunakan sebagai alat dalam meraih kekuasaan politik. ",
  },
  {
    id: 12,
    title: "Laut Bercerita",
    author: "Leila S. Chudori",
    year: 2017,
    cover: "https://narasigardapena.com/wp-content/uploads/2025/05/photo_2025-05-01_13-12-29.jpg",
    subject: "Novel Fiksi",
    description: "Menceritakan tentang kisah kekejaman rezim Orde Baru dan hilangnya para aktivis mahasiswa, di mana sebagian besar cerita berfokus pada perjuangan dan penghilangan paksa mereka.",
  },
  {
    id: 13,
    title: "Madilog",
    author: "Tan Malaka",
    year: 1951,
    cover: "https://i.pinimg.com/736x/4d/d3/58/4dd358348d18e1c6f4fdfcd9effc19af.jpg",
    subject: "Filsafat",
    description: "Materialisme, dialektika, dan logika untuk mengajak pembaca berpikir secara ilmiah dan rasional, bebas dari takhayul dan dogma. Madilog merupakan karya penting dalam sejarah pemikiran Indonesia yang memadukan filsafat Barat, ilmu alam, dan tradisi lokal.",
  },
];


export default booksData;
